menu title Radxa Rock 5C Lite Boot Menu
timeout 1

label Default Linux
  kernel /boot/Image
  devicetree /boot/rk3582-rock-5c-lite.dtb
  append quiet earlycon console=ttyS2,1500000n8 root=PARTLABEL=rootfs rw rootwait TERM=xterm-256color

label Debug Linux
  kernel /boot/Image
  devicetree /boot/rk3582-rock-5c-lite.dtb
  append initcall_debug log_buf_len=4M earlycon console=ttyS2,1500000n8 root=PARTLABEL=rootfs rw rootwait TERM=xterm-256color
